### ISSUE TITLE
Add a seperate config option for bsc etherscan api key

### ISSUE THREAD

**Issue by seunlanlege** [schmiatz/hyperbridge-relayer#1]
Bsc does not share the same API key with ethereum and it's L2s

https://github.com/schmiatz/hyperbridge-relayer/blob/f78de4471cd59acdcfa9f4ceefa180d662d9f859/roles/hyperbridge-relayer/templates/config.toml.j2#L99

**Comment by schmiatz** [comment]
thank you, added a variable for eth and one for bsc api key on etherscan
