### ISSUE TITLE
Allow users configure more options

### ISSUE THREAD

**Issue by seunlanlege** [schmiatz/hyperbridge-relayer#2]
Would be good to expose more configuration options. eg chain
https://github.com/schmiatz/hyperbridge-relayer/blob/d91891951d48d11893f75b50d878eb558dbefe5d/roles/hyperbridge-relayer/templates/config.toml.j2#L4
https://github.com/schmiatz/hyperbridge-relayer/blob/d91891951d48d11893f75b50d878eb558dbefe5d/roles/hyperbridge-relayer/templates/config.toml.j2#L111

hyperbridge ws rpc endpoint

https://github.com/schmiatz/hyperbridge-relayer/blob/d91891951d48d11893f75b50d878eb558dbefe5d/roles/hyperbridge-relayer/templates/config.toml.j2#L6

minimum_profit_percentage

https://github.com/schmiatz/hyperbridge-relayer/blob/d91891951d48d11893f75b50d878eb558dbefe5d/roles/hyperbridge-relayer/templates/config.toml.j2#L113

**Comment by seunlanlege** [comment]
Wonder if it's possible to match on the chain input and chose the contract addresses based on this input

**Comment by schmiatz** [comment]
so those contracts addresses are for chain= Gargantua, right? https://docs.hyperbridge.network/evm/integration#gargantua-v2

where can i find the addresses for dev, messier or nexus? then i could match like you suggested

**Comment by schmiatz** [comment]
added the variable "chain"

**Comment by schmiatz** [comment]
added variables "hyperbridge_node_ws" and "minimum_profit_percentage"

**Comment by schmiatz** [comment]
to match the chain input with the addresses, i would need your input where to get the addresses for each chain @seunlanlege. the other issues are done

**Comment by seunlanlege** [comment]
> so those contracts addresses are for chain= Gargantua, right? https://docs.hyperbridge.network/evm/integration#gargantua-v2
> 
> where can i find the addresses for dev, messier or nexus? then i could match like you suggested

For now, we're not on mainnet so there are no mainnet contracts for messier or nexus

> to match the chain input with the addresses, i would need your input where to get the addresses for each chain @seunlanlege. the other issues are done

[Gargantua v2 contracts](https://docs.hyperbridge.network/evm/integration#gargantua-v2) should be for the "Gargantua" chain config.

**Comment by schmiatz** [comment]
okay then i will close this issue until we have more possible values for the chain, then i will automatically paste the contract addresses based of the chain
